title: Bilal Mustafa
description: Bachelor of Science in Physics/Mathematics with a passion in applying data science and modelling to explore and discover novel solutions to pertinent issues.
theme: minima
