title: "Data Analytics Portfolio Website"
avatar: "https://github.com/bmustafa225/DA-Website/blob/main/9ada3900-a2d2-49b7-bca9-9d42c5411324.jpg"
round-avatar: True
author: "Bilal Mustafa"
email: "bmustafa@ualberta.ca"
description: "Bachelor of Science in Physics/Mathematics with a passion in applying data science and modelling to explore and discover novel solutions to pertinent issues."
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
